/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import datos.DatabaseManager;
import java.awt.Color;
import java.awt.Image;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.IOException;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import org.jvnet.substance.SubstanceLookAndFeel;
//import negocio.ReporteProductos;
//import net.sf.jasperreports.engine.JRException;
//import org.jvnet.substance.SubstanceLookAndFeel;

/**
 *
 * @author pablo
 */
public class menu extends javax.swing.JFrame {

    public int estado = 0;
    ImageIcon[] iconcliente = new ImageIcon[4];
    Color color = new Color(153, 153, 255);
    VentanaProducto vproducto;
    VentanaFactura vfactura;
    VentanaCliente vcliente;

    public menu() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
        SubstanceLookAndFeel.setSkin("org.jvnet.substance.skin.CremeCoffeeSkin");
        inicializarBotones();
        blqueomenu(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar3 = new javax.swing.JToolBar();
        bclientes = new javax.swing.JButton();
        bproducto = new javax.swing.JButton();
        jToolBar4 = new javax.swing.JToolBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        jToolBar2 = new javax.swing.JToolBar();
        bvender = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        jXTaskPane1 = new org.jdesktop.swingx.JXTaskPane();
        bguardar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bnuevo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        bmodificar = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        beleminar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistemas de Ventas");

        jToolBar3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ingresos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 10))); // NOI18N
        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        bclientes.setText("    Clientes    ");
        bclientes.setFocusable(false);
        bclientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bclientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bclientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclientesActionPerformed(evt);
            }
        });
        jToolBar3.add(bclientes);

        bproducto.setText("    Producto    ");
        bproducto.setFocusable(false);
        bproducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bproducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bproductoActionPerformed(evt);
            }
        });
        jToolBar3.add(bproducto);

        jToolBar4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Herramientas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 10))); // NOI18N
        jToolBar4.setFloatable(false);
        jToolBar4.setRollover(true);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("Calculadora");
        jButton1.setFocusable(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton1);

        jButton2.setText("    Ayuda    ");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar4.add(jButton2);

        jButton8.setText("    Salir   ");
        jButton8.setFocusable(false);
        jButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jToolBar4.add(jButton8);

        jToolBar2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Ventas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("Arial", 0, 10))); // NOI18N
        jToolBar2.setFloatable(false);
        jToolBar2.setRollover(true);

        bvender.setText("   Vender   ");
        bvender.setFocusable(false);
        bvender.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bvender.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bvender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bvenderActionPerformed(evt);
            }
        });
        jToolBar2.add(bvender);

        jButton7.setText("Facturas");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar2.add(jButton7);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        jXTaskPane1.setAnimated(false);
        jXTaskPane1.setSpecial(true);
        jXTaskPane1.setTitle("Herramientas");
        jXTaskPane1.setDoubleBuffered(false);
        jXTaskPane1.setEnabled(false);
        jXTaskPane1.setFocusTraversalPolicyProvider(true);
        jXTaskPane1.setOpaque(true);
        jXTaskPane1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jXTaskPane1MouseMoved(evt);
            }
        });

        bguardar.setBackground(javax.swing.UIManager.getDefaults().getColor("ComboBox.selectionBackground"));
        bguardar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bguardar.setText("Guardar");
        bguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bguardar.setOpaque(true);
        bguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bguardarMouseClicked(evt);
            }
        });
        bguardar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bguardarMouseMoved(evt);
            }
        });
        jXTaskPane1.getContentPane().add(bguardar);
        jXTaskPane1.getContentPane().add(jSeparator1);

        bnuevo.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        bnuevo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bnuevo.setText("Nuevo");
        bnuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bnuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bnuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bnuevoMouseClicked(evt);
            }
        });
        bnuevo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bnuevoMouseMoved(evt);
            }
        });
        jXTaskPane1.getContentPane().add(bnuevo);
        jXTaskPane1.getContentPane().add(jSeparator2);

        bmodificar.setBackground(new java.awt.Color(51, 153, 255));
        bmodificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bmodificar.setText("Modificar");
        bmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bmodificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bmodificarMouseClicked(evt);
            }
        });
        bmodificar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                bmodificarMouseMoved(evt);
            }
        });
        jXTaskPane1.getContentPane().add(bmodificar);
        jXTaskPane1.getContentPane().add(jSeparator3);

        beleminar.setBackground(new java.awt.Color(51, 153, 255));
        beleminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        beleminar.setText("Eliminar");
        beleminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        beleminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        beleminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                beleminarMouseClicked(evt);
            }
        });
        beleminar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                beleminarMouseMoved(evt);
            }
        });
        jXTaskPane1.getContentPane().add(beleminar);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTaskPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jXTaskPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToolBar4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1020, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jToolBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(escritorio, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 29, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXTaskPane1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jXTaskPane1MouseMoved
        // TODO add your handling code here:
        inicializarBotones();
    }//GEN-LAST:event_jXTaskPane1MouseMoved
    public void iconos(int op) {
        for (int i = 0; i < 4; i++) {
            if (op == 1) {
                iconcliente[i] = new ImageIcon(getClass().getResource("/imagenes/group" + i + ".png"));
            } else {
                iconcliente[i] = new ImageIcon(getClass().getResource("/imagenes/brick" + i + ".png"));
            }
        }
        bguardar.setIcon(iconcliente[0]);
        bnuevo.setIcon(iconcliente[1]);
        bmodificar.setIcon(iconcliente[2]);
        beleminar.setIcon(iconcliente[3]);
    }

    public void blqueomenu(boolean f) {
        bguardar.setEnabled(f);
        bnuevo.setEnabled(f);
        bmodificar.setEnabled(f);
        beleminar.setEnabled(f);

    }
    private void bguardarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bguardarMouseMoved
        bguardar.setBackground(color);
        bguardar.setOpaque(true);        // TODO add your handling code here:
    }//GEN-LAST:event_bguardarMouseMoved

    private void bnuevoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnuevoMouseMoved
        bnuevo.setBackground(color);
        bnuevo.setOpaque(true);
    }//GEN-LAST:event_bnuevoMouseMoved

    private void bmodificarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmodificarMouseMoved
        // TODO add your handling code here:
        bmodificar.setBackground(color);
        bmodificar.setOpaque(true);
    }//GEN-LAST:event_bmodificarMouseMoved

    private void beleminarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beleminarMouseMoved
        // TODO add your handling code here:
        beleminar.setBackground(color);
        beleminar.setOpaque(true);
    }//GEN-LAST:event_beleminarMouseMoved

    private void bclientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclientesActionPerformed
        estado = 1; //boton de clientes activa
        vcliente = new VentanaCliente();
        escritorio.add(vcliente);
        vcliente.show();
        blqueomenu(true);
        iconos(1);
    }//GEN-LAST:event_bclientesActionPerformed

    private void bproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bproductoActionPerformed

        estado = 2; //boton de productos activa
        vproducto = new VentanaProducto();
        escritorio.add(vproducto);
        vproducto.show();
        blqueomenu(true);
        iconos(2);
    }//GEN-LAST:event_bproductoActionPerformed

    private void bguardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bguardarMouseClicked
        if (estado == 1) {
            vcliente.Grabar();
        } else if (estado == 2) {
            vproducto.Grabar();
        }
    }//GEN-LAST:event_bguardarMouseClicked

    private void bnuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bnuevoMouseClicked
        if (estado == 1) {
            vcliente.nuevo();
        } else if (estado == 2) {
            vproducto.nuevo();
        }
    }//GEN-LAST:event_bnuevoMouseClicked

    private void bmodificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bmodificarMouseClicked
        if (estado == 1) {
            vcliente.Modificar();
        } else if (estado == 2) {
            vproducto.modificar();
        }
    }//GEN-LAST:event_bmodificarMouseClicked

    private void beleminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_beleminarMouseClicked
        if (estado == 1) {
            vcliente.Eliminar();
        } else if (estado == 2) {
            vproducto.eliminar();
        }
    }//GEN-LAST:event_beleminarMouseClicked
///hola
    private void bvenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bvenderActionPerformed
        try {
            estado = 3; //boton de productos activa
            vfactura = new VentanaFactura();
            escritorio.add(vfactura);
            vfactura.show();
            //        blqueomenu(true);
        } catch (SQLException ex) {
            Logger.getLogger(menu.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_bvenderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            Runtime rt = Runtime.getRuntime();
            Process p = rt.exec("calc");
            p.waitFor();
        } catch (IOException ioe) {
            ioe.printStackTrace();
        } catch (InterruptedException ie) {
            ie.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        estado = 4; //boton de productos activa
        FacturasLista f = new FacturasLista(this);
        escritorio.add(f);
        f.show();
        //        blqueomenu(true);



    }//GEN-LAST:event_jButton7ActionPerformed
    public void inicializarBotones() {
        bguardar.setBackground(Color.red);
        bnuevo.setBackground(Color.red);
        bmodificar.setBackground(Color.red);
        beleminar.setBackground(Color.red);
        bguardar.setOpaque(false);
        bnuevo.setOpaque(false);
        bmodificar.setOpaque(false);
        beleminar.setOpaque(false);
    }

    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bclientes;
    private javax.swing.JLabel beleminar;
    private javax.swing.JLabel bguardar;
    private javax.swing.JLabel bmodificar;
    private javax.swing.JLabel bnuevo;
    private javax.swing.JButton bproducto;
    private javax.swing.JButton bvender;
    public javax.swing.JDesktopPane escritorio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JToolBar jToolBar4;
    private org.jdesktop.swingx.JXTaskPane jXTaskPane1;
    private javax.swing.JPanel panel1;
    // End of variables declaration//GEN-END:variables
}
